name = "order-system"
compatibility_date = "2025-12-02"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "order-system-db"
database_id = "TUTAJ-WPISZ-ID-PO-STWORZENIU-BAZY"
